ALTER TABLE cohorts ADD COLUMN IF NOT EXISTS is_open BOOLEAN DEFAULT true;
ALTER TABLE cohorts ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE cohorts ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE cohorts ADD COLUMN IF NOT EXISTS is_recruiting BOOLEAN DEFAULT false;
ALTER TABLE cohorts ADD COLUMN IF NOT EXISTS recruit_link TEXT;

UPDATE cohorts SET is_open = true WHERE is_open IS NULL;
